---
- name: Install pre-requisites
  apt:
    name:
      - ruby2.1
    update_cache: yes

- name: Download codedeploy-agent
  get_url:
    url: "http://aws-codedeploy-eu-west-1.s3-eu-west-1.amazonaws.com/latest/install"
    dest: "/tmp/"
    mode: 0744

- name: Install codedeploy-agent
  command: "/tmp/install auto"
  become: yes

- name: Cleanup codedeploy-agent deb
  file:
    path: "/tmp/install"
    state: absent
  become: yes

- name: Create codedeploy-agent config
  copy:
    src: "etc-codedeploy-agent-conf-codedeployagent.yml"
    dest: "/etc/codedeploy-agent/conf/codedeployagent.yml"
  become: yes

- name: Create codedeploy-agent init script
  copy:
    src: "etc-init.d-codedeploy-agent.service"
    dest: "/etc/init.d/codedeploy-agent"
    mode: 0744
  become: yes

- name: Start codedeploy-agent at boot
  command: update-rc.d codedeploy-agent enable
  become: yes
