---
- name: Install pre-requisites
  apt:
    name:
      - ruby2.1
    update_cache: yes

- name: Create ruby symlink
  file:
    path: /usr/bin/ruby
    src: /usr/bin/ruby2.1
    state: link

- name: Download codedeploy-agent
  get_url:
    url: "http://aws-codedeploy-eu-west-1.s3-eu-west-1.amazonaws.com/latest/install"
    dest: "/tmp/"
    mode: 0744

- name: Install codedeploy-agent
  command: "/tmp/install deb"
  become: yes

- name: Cleanup codedeploy-agent deb
  file:
    path: "/tmp/install"
    state: absent
  become: yes

- name: Create codedeploy-agent init script
  copy:
    src: "etc-init.d-codedeploy-agent.service"
    dest: "/etc/systemd/system/codedeploy-agent.service"
    mode: 0744
  become: yes

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes
  notify:
    - restart codedeploy
